name: "security/deps"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency-review
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5
        with:
          fail-on-severity: high
          allow-dependencies-licenses: >-
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-jsonc.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-js.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-shell.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-yaml.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-python.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks-terraform.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/security-secrets.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/security-deps.yml,
            pkg:githubactions/mathewmusango/my-workflows/.github/workflows/checks.yml
