name: security

on:
  workflow_call:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: ./.github/workflows/security-gitleaks.yml
  deps:
    uses: ./.github/workflows/security-deps.yml
  terraform:
    uses: ./.github/workflows/security-terraform.yml
